spring:
  port: 8080
  sms:
    domain: dysmsapi.aliyuncs.com
    version: 2017-05-25
    regionId: cn-hangzhou
    signName: LittleCadet
    templateCode: SMS_181851404
    # 正确的key为LTAI4FtqaYhp88W4UvyJEjej
    accessKeyId: LTAI4FtqaYhp88W4UvyJEjea
    secret: bJtzYDi3IPfjMDHdBeW8UhE4QAZlRZ