# MySQL
mysql:
  db:
    host: 47.99.112.38
    port: 3306
    username: normal
    password: Sx920702

# Redis
spring:
  redis:
    host: 47.99.112.38
    port: 6379
    password: cmVkaXNPZkVkd2FyZFNoZW4=
    timeout: 30000
    database: 0

    pool:
      max-size: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0


