spring:
  application:
    name: jedis_server

  # 这是profiles ！
  profiles:
    active: dev
  main:
    # 制作SpringBoot的图的网站：http://patorjk.com/software/taag
    ## 三种方式：console【打印到控制台】,log【打印到日志】,"off"【关闭】
    banner-mode: log

  devtools:
    restart:
      enabled: false


server:
  port: 8080
  tomcat:
    max-connections: 10000
    accept-count: 100
    connection-timeout: 60000
    max-threads: 500
    min-spare-threads: 30
    max-queue-size: 100
    max-idle-time: 60000


