spring:
  application:
    name: error_server

  datasource:
    hikari:
      #用于表示每次建立连接时，先查询select 1 判定该连接是否可用
      connection-test-query: SELECT 1
      #连接池最小空闲的连接数
      minimum-idle: 1
      #连接池最大的连接数
      maximum-pool-size: 5
    #驱动器
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.47.114:3306/facemall?autoReconnect=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: vL0jl8B5qnelAlOK
    #数据源的类型
    type: com.zaxxer.hikari.HikariDataSource


server:
  port: 8080
  tomcat:
    max-connections: 10000
    accept-count: 100
    connection-timeout: 60000
    max-threads: 500
    min-spare-threads: 30
    max-queue-size: 100
    max-idle-time: 60000


